import assert from "node:assert/strict";
import { test } from "node:test";
import type { Proposal } from "@magpie/core";
import { makeTestContext } from "../../test-support/context.js";
import { createProposalFromCompletedJob, maybeRegenerateStaleProposal, REGENERATION_CAP } from "./service.js";
import type { AppContext } from "../../context.js";

// A published, still-open proposal with an open PR — the state a stale PR is in.
async function seedPublished(ctx: AppContext, overrides: Partial<Proposal> = {}): Promise<Proposal> {
  const created = await ctx.stores.proposals.create({
    title: "Widgets guide",
    targetPath: "docs/widgets.md",
    markdown: "# Widgets\n\nold body",
    rationale: "closes the widgets gap",
    evidence: [],
    gapSummary: "how do widgets work"
  });
  const published = await ctx.stores.proposals.recordPublication(created.id, {
    provider: "local-git",
    branchName: `magpie/proposal-${created.id.slice(0, 8)}-widgets-guide`,
    commitSha: "abc123",
    pullRequestUrl: "https://github.com/o/r/pull/9",
    publishedAt: "2026-07-01T00:00:00.000Z"
  });
  assert.ok(published);
  if (Object.keys(overrides).length === 0) {
    return published;
  }
  // Apply any status/reviewDecision/regenerationCount overrides the test needs.
  const store = ctx.stores.proposals as unknown as { proposals: Map<string, Proposal> };
  const merged = { ...published, ...overrides };
  store.proposals.set(published.id, merged);
  return merged;
}

async function draftJobs(ctx: AppContext) {
  return (await ctx.jobs.list({ type: "draft_markdown_proposal", limit: 100 })).jobs;
}

test("a conflicting PR enqueues a regeneration draft keyed to the proposal", async () => {
  const ctx = makeTestContext();
  const proposal = await seedPublished(ctx);

  await maybeRegenerateStaleProposal(ctx, proposal.id);

  const jobs = await draftJobs(ctx);
  assert.equal(jobs.length, 1);
  const input = jobs[0].input as { regenerateProposalId?: string; targetPath?: string };
  assert.equal(input.regenerateProposalId, proposal.id);
  // Target path is kept stable so the branch/PR stay put.
  assert.equal(input.targetPath, "docs/widgets.md");
});

test("an approved PR is left for a human, not regenerated", async () => {
  const ctx = makeTestContext();
  const proposal = await seedPublished(ctx, { reviewDecision: "approved" });

  await maybeRegenerateStaleProposal(ctx, proposal.id);

  assert.equal((await draftJobs(ctx)).length, 0);
});

test("a proposal at the regeneration cap is not regenerated again", async () => {
  const ctx = makeTestContext();
  const proposal = await seedPublished(ctx, { regenerationCount: REGENERATION_CAP });

  await maybeRegenerateStaleProposal(ctx, proposal.id);

  assert.equal((await draftJobs(ctx)).length, 0);
});

test("a changeset (multi-file) proposal is not regenerated by this path", async () => {
  const ctx = makeTestContext();
  const proposal = await seedPublished(ctx, {
    changeset: [{ path: "docs/a.md", content: "a" }]
  });

  await maybeRegenerateStaleProposal(ctx, proposal.id);

  assert.equal((await draftJobs(ctx)).length, 0);
});

test("a second regeneration is not stacked while one is in flight", async () => {
  const ctx = makeTestContext();
  const proposal = await seedPublished(ctx);

  await maybeRegenerateStaleProposal(ctx, proposal.id);
  await maybeRegenerateStaleProposal(ctx, proposal.id);

  assert.equal((await draftJobs(ctx)).length, 1);
});

test("completing a regeneration draft updates the proposal in place and re-publishes", async () => {
  const ctx = makeTestContext();
  const proposal = await seedPublished(ctx);

  // Enqueue the regeneration so a real job (with regenerateProposalId) exists.
  await maybeRegenerateStaleProposal(ctx, proposal.id);
  const [job] = await draftJobs(ctx);

  const updated = await createProposalFromCompletedJob(ctx, job, {
    title: "Widgets guide v2",
    targetPath: "docs/renamed.md",
    markdown: "# Widgets\n\nfresh body",
    rationale: "regenerated"
  });
  // The regeneration branch returns undefined so the caller skips the at-draft fold.
  assert.equal(updated, undefined);

  const after = await ctx.stores.proposals.get(proposal.id);
  assert.ok(after);
  assert.equal(after.markdown, "# Widgets\n\nfresh body");
  // Title and targetPath stay stable — the redraft's new title/path are ignored so
  // the branch and PR do not move.
  assert.equal(after.title, "Widgets guide");
  assert.equal(after.targetPath, "docs/widgets.md");
  assert.equal(after.regenerationCount, 1);

  const publishJobs = (await ctx.jobs.list({ type: "publish_proposal", limit: 10 })).jobs;
  assert.equal(publishJobs.length, 1);
  const publishInput = publishJobs[0].input as { regenerate?: boolean; proposalId: string };
  assert.equal(publishInput.regenerate, true);
  assert.equal(publishInput.proposalId, proposal.id);
});
