import type { CrunchFileWrite, CrunchOperation, CrunchPlan } from "./index.js";

function crunchSlug(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60)
      .replace(/-+$/g, "") || "section"
  );
}

function documentFolder(filePath: string): string {
  const segments = filePath.replace(/\\/g, "/").split("/");
  return segments.length > 1 ? segments.slice(0, -1).join("/") : "";
}

function countHeadings(content: string, level: number): string[] {
  const prefix = `${"#".repeat(level)} `;
  return content
    .split(/\r?\n/)
    .filter((line) => line.startsWith(prefix))
    .map((line) => line.slice(prefix.length).trim())
    .filter(Boolean);
}

// Deterministic, dependency-free tidy heuristics shared by the API's direct
// mock executor and the watcher's mock runner so demos and tests agree:
//   - SPLIT a document that has grown large (> 1,800 chars) and covers several
//     topics (>= 3 level-2 headings) into one file per "##" section.
//   - CONSOLIDATE a folder that has fragmented into several small documents
//     (>= 2 docs, each < 1,200 chars, none being split) into one overview file.
// Real providers replace this with a model call; the shape of the output is the
// same CrunchPlan either way.
export function buildMockCrunchPlan(documents: CrunchFileWrite[]): CrunchPlan {
  const operations: CrunchOperation[] = [];
  const splitPaths = new Set<string>();

  for (const document of [...documents].sort((left, right) => left.path.localeCompare(right.path))) {
    const sections = countHeadings(document.content, 2);
    if (document.content.length <= 1800 || sections.length < 3) {
      continue;
    }

    splitPaths.add(document.path);
    const folder = documentFolder(document.path);
    const baseName = (document.path.replace(/\\/g, "/").split("/").at(-1) ?? document.path).replace(/\.md$/i, "");
    const baseDir = folder ? `${folder}/${crunchSlug(baseName)}` : crunchSlug(baseName);
    const blocks = splitByHeading(document.content, 2);
    const writes: CrunchFileWrite[] = blocks.map((block) => ({
      path: `${baseDir}/${crunchSlug(block.heading)}.md`,
      content: `# ${block.heading}\n\n${block.body.trim()}\n`
    }));

    operations.push({
      kind: "split",
      title: `Split ${document.path} into ${writes.length} focused documents`,
      reason: `This document is ${document.content.length} characters across ${sections.length} top-level sections, mixing several topics. Splitting one section per file keeps each document focused and easier to retrieve.`,
      sources: [document.path],
      writes,
      deletes: [document.path]
    });
  }

  const byFolder = new Map<string, CrunchFileWrite[]>();
  for (const document of documents) {
    if (splitPaths.has(document.path)) {
      continue;
    }
    if (document.content.length >= 1200) {
      continue;
    }
    const folder = documentFolder(document.path);
    byFolder.set(folder, [...(byFolder.get(folder) ?? []), document]);
  }

  for (const [folder, folderDocuments] of [...byFolder.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    if (folderDocuments.length < 2) {
      continue;
    }

    const sorted = [...folderDocuments].sort((left, right) => left.path.localeCompare(right.path));
    const overviewPath = folder ? `${folder}/overview.md` : "overview.md";
    const heading = folder ? `${folder} overview` : "Overview";
    const body = sorted
      .map((document) => {
        const title = (document.path.replace(/\\/g, "/").split("/").at(-1) ?? document.path).replace(/\.md$/i, "");
        return `## ${title}\n\n${stripFrontmatter(document.content).trim()}`;
      })
      .join("\n\n");

    operations.push({
      kind: "consolidate",
      title: `Consolidate ${sorted.length} small documents in ${folder || "the root"} into one overview`,
      reason: `${sorted.length} short documents (each under 1,200 characters) cover closely related material in the same folder. Merging them into a single overview reduces fragmentation and duplicate context.`,
      sources: sorted.map((document) => document.path),
      writes: [{ path: overviewPath, content: `# ${heading}\n\n${body}\n` }],
      deletes: sorted.map((document) => document.path)
    });
  }

  return {
    summary:
      operations.length === 0
        ? "The knowledge base already looks tidy — no consolidations or splits are needed."
        : `${operations.length} tidy operation(s): ${operations.filter((operation) => operation.kind === "split").length} split, ${operations.filter((operation) => operation.kind === "consolidate").length} consolidate.`,
    operations,
    rationale: "Generated by the deterministic mock crunch planner from document size and folder fragmentation heuristics."
  };
}

function stripFrontmatter(content: string): string {
  const match = /^---\r?\n[\s\S]*?\r?\n---\r?\n?/.exec(content);
  return match ? content.slice(match[0].length) : content;
}

function splitByHeading(content: string, level: number): Array<{ heading: string; body: string }> {
  const prefix = `${"#".repeat(level)} `;
  const lines = stripFrontmatter(content).split(/\r?\n/);
  const blocks: Array<{ heading: string; body: string }> = [];
  let current: { heading: string; body: string[] } | undefined;

  for (const line of lines) {
    if (line.startsWith(prefix)) {
      if (current) {
        blocks.push({ heading: current.heading, body: current.body.join("\n") });
      }
      current = { heading: line.slice(prefix.length).trim() || "Section", body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }

  if (current) {
    blocks.push({ heading: current.heading, body: current.body.join("\n") });
  }

  return blocks;
}
